/**
 * Regression guard for the fixture-playback unification: `src/scenarios/fixturePlayback.ts`'s
 * `expandFixtureToSteps` must derive its `Step[]` purely from `src/fixture/planner.ts`'s
 * `planPlayback`, never by re-deriving the delay-mode arithmetic itself. This spec proves the two
 * outputs agree, for every fixture under `fixtures/`, so the two paths can never silently drift
 * apart again.
 *
 * The cross-check loop below (`expandFixtureToSteps agrees with planPlayback`) only proves the two
 * paths agree WITH EACH OTHER; it cannot catch a bug shared by both, because `expandFixtureToSteps`
 * calls `planPlayback` internally. The `hand-computed expected schedules` and `regression: `
 * describe blocks further down are what actually pin the arithmetic: their expected
 * `(deliverAtMs, timestampIso, atSec)` triples are written out by hand from each fixture's own
 * JSON, never generated by `planPlayback` or `expandFixtureToSteps`, so a sign error or an
 * off-by-one inside `planner.ts` (a flipped `BURST_STEP_MS`, a `<=` that should be `<`, a
 * mis-defaulted `burstStartAtSec`, a dropped absolute offset on the first item, an implicit rather
 * than explicit tie-break) has somewhere to actually fail.
 *
 * Deliberately NOT tagged `@mutating` (see `playwright.config.ts`'s `grepInvert`) and lives under
 * the `unit` project (`playwright.config.ts`), which has no `preflight` dependency: it calls
 * `planPlayback`/`expandFixtureToSteps`/`listFixtures` directly, all pure, in-process, file-reading
 * functions. No `ApiClient`, no HTTP, no database — it makes no network calls at all.
 */
import { test, expect } from '@playwright/test';
import { listFixtures, loadFixture } from '../../src/fixture/loader';
import { planPlayback } from '../../src/fixture/planner';
import { expandFixtureToSteps } from '../../src/scenarios/fixturePlayback';
import type { Step } from '../../src/scenario/types';

/** Fixed anchor so both paths resolve the exact same absolute timestamps run to run, and so every
 *  fixture in this file is anchored explicitly rather than through `planner.ts`'s own default
 *  (`opts.t0` always wins over the fixture-derived default — see `planner.ts`'s `defaultAnchor`). */
const T0 = new Date('2026-01-01T00:00:00.000Z');

/** The `PlannedEvent.kind` a compiled `Step` corresponds to. */
function stepKind(step: Step): 'trip' | 'ident' {
  return step.kind === 'ident' ? 'ident' : 'trip';
}

/** The GMS event type a non-ident `Step` corresponds to, for a stronger identity check than kind alone. */
function stepGmsType(step: Step): string | undefined {
  switch (step.kind) {
    case 'ignitionOn':
      return 'IGN_ON';
    case 'ignitionOff':
      return 'IGN_OFF';
    case 'move':
      return 'ON_PERIODIC';
    case 'harshEvent':
      return { hardBrake: 'HARDBRAKE', hardAccel: 'HARDACCEL', hardTurn: 'HARDTURN' }[step.severity ?? 'hardBrake'];
    default:
      return undefined;
  }
}

const fixtures = listFixtures();

test.describe('expandFixtureToSteps agrees with planPlayback', () => {
  for (const fixture of fixtures) {
    // `id` alone is not unique: O6 and O12c each ship two fixture files (multi-part cases) that
    // share one case id, so the title includes `title` too, which does distinguish them.
    test(`${fixture.id} — ${fixture.title}: same ordering and absolute delivery schedule as planPlayback`, () => {
      const plan = planPlayback(fixture, { t0: T0 });
      const steps = expandFixtureToSteps(fixture, { t0: T0 });

      expect(steps.length).toBe(plan.events.length);

      // Absolute deliverAtMs, not offsets relative to the first item: the FIRST step's own
      // sendAfterMs must be honoured too (defect: `expandFixtureToSteps` used to force it to zero,
      // silently dropping a fixture's own lead time — see O5/O12d below, which pin this down with
      // a concrete number rather than only a cross-check against `plan`).
      let cumulativeMs = 0;

      for (let i = 0; i < steps.length; i++) {
        const step = steps[i];
        const plannedItem = plan.events[i];
        if (!step || !plannedItem) throw new Error(`missing item at index ${i}`);

        // Same ordering: each compiled step corresponds to the same planned item, by kind and,
        // for trip events, by the concrete GMS event/severity it carries; for identifications, by
        // the driver it names.
        expect(stepKind(step)).toBe(plannedItem.kind);
        if (plannedItem.kind === 'trip') {
          expect(stepGmsType(step)).toBe(plannedItem.tripEvent?.type);
        } else if (step.kind === 'ident') {
          expect(step.driver).toBe(plannedItem.identification?.driver ?? null);
        }

        // Same absolute delivery offset: summing every step's own `sendAfterMs` (including the
        // first) reproduces `planPlayback`'s absolute `deliverAtMs` exactly.
        cumulativeMs += step.sendAfterMs ?? 0;
        expect(cumulativeMs).toBe(plannedItem.deliverAtMs);
      }
    });
  }

  test('every fixture under fixtures/ was exercised', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });
});

interface ExpectedItem {
  kind: 'trip' | 'ident';
  label: string;
  deliverAtMs: number;
  timestampIso: string;
  atSec: number;
}

/** Asserts `plan`/`steps` against a hand-written table, independent of any code under test. */
function assertMatchesHandTable(fixtureId: string, plan: ReturnType<typeof planPlayback>, steps: Step[], expected: ExpectedItem[]): void {
  expect(plan.events.length, `${fixtureId}: plan.events length`).toBe(expected.length);
  expect(steps.length, `${fixtureId}: steps length`).toBe(expected.length);

  let cumulativeMs = 0;
  for (let i = 0; i < expected.length; i++) {
    const row = expected[i];
    const plannedItem = plan.events[i];
    const step = steps[i];
    if (!row || !plannedItem || !step) throw new Error(`${fixtureId}: missing item at index ${i}`);

    expect(plannedItem.kind, `${fixtureId}[${i}] (${row.label}) plannedItem.kind`).toBe(row.kind);
    expect(plannedItem.deliverAtMs, `${fixtureId}[${i}] (${row.label}) deliverAtMs`).toBe(row.deliverAtMs);
    expect(plannedItem.timestampIso, `${fixtureId}[${i}] (${row.label}) timestampIso`).toBe(row.timestampIso);

    cumulativeMs += step.sendAfterMs ?? 0;
    expect(cumulativeMs, `${fixtureId}[${i}] (${row.label}) cumulative deliverAtMs from steps`).toBe(row.deliverAtMs);
    expect(step.atSec, `${fixtureId}[${i}] (${row.label}) step.atSec`).toBeCloseTo(row.atSec, 9);
  }
}

test.describe('hand-computed expected schedules (one fixture per delay mode)', () => {
  // Every expected value below is computed by hand from the fixture's own JSON and the delay-mode
  // rules in `fixture/types.ts`'s `DelayMode` doc comment, never by calling `planPlayback` or
  // `expandFixtureToSteps`. T0 = 2026-01-01T00:00:00.000Z throughout.

  test('O2 (delay.mode "none"): trip plays at its own atSec, identification interleaves by time', () => {
    const fixture = loadFixture('O2');
    const plan = planPlayback(fixture, { t0: T0 });
    const steps = expandFixtureToSteps(fixture, { t0: T0 });

    const expected: ExpectedItem[] = [
      { kind: 'trip', label: 'IGN_ON', deliverAtMs: 0, timestampIso: '2026-01-01T00:00:00.000Z', atSec: 0 },
      { kind: 'trip', label: 'HARDBRAKE', deliverAtMs: 30_000, timestampIso: '2026-01-01T00:00:30.000Z', atSec: 30 },
      { kind: 'trip', label: 'ON_PERIODIC@58', deliverAtMs: 58_000, timestampIso: '2026-01-01T00:00:58.000Z', atSec: 58 },
      { kind: 'ident', label: 'driver A', deliverAtMs: 70_000, timestampIso: '2026-01-01T00:01:10.000Z', atSec: 70 },
      { kind: 'trip', label: 'ON_PERIODIC@116', deliverAtMs: 116_000, timestampIso: '2026-01-01T00:01:56.000Z', atSec: 116 },
      { kind: 'trip', label: 'ON_PERIODIC@174', deliverAtMs: 174_000, timestampIso: '2026-01-01T00:02:54.000Z', atSec: 174 },
      { kind: 'trip', label: 'IGN_OFF', deliverAtMs: 180_000, timestampIso: '2026-01-01T00:03:00.000Z', atSec: 180 },
    ];
    assertMatchesHandTable('O2', plan, steps, expected);
  });

  test('O3.1 (delay.mode "full-burst"): identification precedes the whole burst, trip events land 250ms apart', () => {
    const fixture = loadFixture('O3.1');
    const plan = planPlayback(fixture, { t0: T0 });
    const steps = expandFixtureToSteps(fixture, { t0: T0 });

    // burstStartAtSec: 20 -> burstStartMs 20_000, BURST_STEP_MS 250, 5 trip events.
    const expected: ExpectedItem[] = [
      { kind: 'ident', label: 'driver A, on the wire early', deliverAtMs: 0, timestampIso: '2026-01-01T00:01:10.000Z', atSec: 70 },
      { kind: 'trip', label: 'IGN_ON', deliverAtMs: 20_000, timestampIso: '2026-01-01T00:00:00.000Z', atSec: 0 },
      { kind: 'trip', label: 'ON_PERIODIC@58', deliverAtMs: 20_250, timestampIso: '2026-01-01T00:00:58.000Z', atSec: 58 },
      { kind: 'trip', label: 'HARDBRAKE@95', deliverAtMs: 20_500, timestampIso: '2026-01-01T00:01:35.000Z', atSec: 95 },
      { kind: 'trip', label: 'ON_PERIODIC@116', deliverAtMs: 20_750, timestampIso: '2026-01-01T00:01:56.000Z', atSec: 116 },
      { kind: 'trip', label: 'IGN_OFF', deliverAtMs: 21_000, timestampIso: '2026-01-01T00:02:30.000Z', atSec: 150 },
    ];
    assertMatchesHandTable('O3.1', plan, steps, expected);
  });

  test('O3.3 (delay.mode "partial-burst"): burst covers atSec<=58, the live tail keeps its own absolute atSec', () => {
    const fixture = loadFixture('O3.3');
    const plan = planPlayback(fixture, { t0: T0 });
    const steps = expandFixtureToSteps(fixture, { t0: T0 });

    // burstThroughAtSec: 58, burstStartAtSec: 0 -> IGN_ON and ON_PERIODIC@58 burst at 0ms/250ms;
    // HARDBRAKE@95, ON_PERIODIC@116 and IGN_OFF@170 are the live tail, each at its own atSec*1000
    // (defect 5's chosen reading: the tail never re-bases its clock off the burst's own end).
    const expected: ExpectedItem[] = [
      { kind: 'trip', label: 'IGN_ON (burst)', deliverAtMs: 0, timestampIso: '2026-01-01T00:00:00.000Z', atSec: 0 },
      { kind: 'trip', label: 'ON_PERIODIC@58 (burst)', deliverAtMs: 250, timestampIso: '2026-01-01T00:00:58.000Z', atSec: 58 },
      { kind: 'trip', label: 'HARDBRAKE@95 (live tail)', deliverAtMs: 95_000, timestampIso: '2026-01-01T00:01:35.000Z', atSec: 95 },
      { kind: 'trip', label: 'ON_PERIODIC@116 (live tail)', deliverAtMs: 116_000, timestampIso: '2026-01-01T00:01:56.000Z', atSec: 116 },
      { kind: 'trip', label: 'IGN_OFF@170 (live tail)', deliverAtMs: 170_000, timestampIso: '2026-01-01T00:02:50.000Z', atSec: 170 },
      { kind: 'ident', label: 'driver A, arrives after trip end', deliverAtMs: 200_000, timestampIso: '2026-01-01T00:01:20.000Z', atSec: 80 },
    ];
    assertMatchesHandTable('O3.3', plan, steps, expected);
  });
});

test.describe('regression: defect 3 — the first step\'s absolute delivery offset is honoured', () => {
  // O5's only item is an identification at deliverAtSec 60 with no trip events at all. The
  // previous `expandFixtureToSteps` forced index 0's gap to zero regardless of this, so the
  // compiled step fired immediately instead of 60 real seconds into playback -- silently
  // disagreeing with `player.ts`, which always honoured the absolute offset. Same shape as O12d.
  for (const fixtureId of ['O5', 'O12d'] as const) {
    test(`${fixtureId}: the sole (first) step carries sendAfterMs 60000, not undefined/0`, () => {
      const fixture = loadFixture(fixtureId);
      const plan = planPlayback(fixture, { t0: T0 });
      const steps = expandFixtureToSteps(fixture, { t0: T0 });

      expect(plan.events.length).toBe(1);
      expect(plan.events[0]?.deliverAtMs).toBe(60_000);

      expect(steps.length).toBe(1);
      expect(steps[0]?.sendAfterMs).toBe(60_000);
    });
  }
});

test.describe('regression: defect 4 — explicit tie-break at equal deliverAtMs', () => {
  // O14: the identification (atSec -120, deliverAtSec 0) and the trip's own IGN_ON (atSec 0, mode
  // "none" so deliverAtMs 0 too) are delivered at the exact same offset. The rule
  // (`planner.ts`'s `declaredOrder`) is that trip events sort first; this pins that down as an
  // explicit, tested policy rather than an accident of Array.prototype.sort's stability.
  test('O14: IGN_ON and the identification tie at deliverAtMs 0; IGN_ON sorts first', () => {
    const fixture = loadFixture('O14');
    const plan = planPlayback(fixture, { t0: T0 });
    const steps = expandFixtureToSteps(fixture, { t0: T0 });

    const first = plan.events[0];
    const second = plan.events[1];
    if (!first || !second) throw new Error('O14: expected at least two planned events');

    expect(first.deliverAtMs).toBe(0);
    expect(second.deliverAtMs).toBe(0);
    expect(first.kind).toBe('trip');
    expect(first.tripEvent?.type).toBe('IGN_ON');
    expect(second.kind).toBe('ident');

    expect(stepKind(steps[0]!)).toBe('trip');
    expect(stepGmsType(steps[0]!)).toBe('IGN_ON');
    expect(stepKind(steps[1]!)).toBe('ident');
  });
});

test.describe('expandFixtureToSteps atSecOffset', () => {
  // O2 has a plain trip plus one identification, all delay mode 'none' — enough shape to prove
  // the offset arithmetic without any burst-mode interaction. Its first item's own deliverAtMs is
  // already 0 (IGN_ON at atSec 0), so these tests do not by themselves cover defect 3's fix; see
  // the "regression: defect 3" block above for a fixture whose first item is NOT at offset 0.
  const fixture = loadFixture('O2');
  const ATSEC_OFFSET = 45;

  test('defaults to no offset: identical to omitting the option', () => {
    const withoutOpts = expandFixtureToSteps(fixture, { t0: T0 });
    const withZeroOffset = expandFixtureToSteps(fixture, { t0: T0, atSecOffset: 0 });
    expect(withZeroOffset).toEqual(withoutOpts);
  });

  test('shifts every step\'s atSec by the offset, in the same order', () => {
    const base = expandFixtureToSteps(fixture, { t0: T0 });
    const offset = expandFixtureToSteps(fixture, { t0: T0, atSecOffset: ATSEC_OFFSET });

    expect(offset.length).toBe(base.length);
    for (let i = 0; i < base.length; i++) {
      const baseStep = base[i];
      const offsetStep = offset[i];
      if (!baseStep || !offsetStep) throw new Error(`missing step at index ${i}`);
      expect(stepKind(offsetStep)).toBe(stepKind(baseStep));
      expect(offsetStep.atSec).toBeCloseTo(baseStep.atSec + ATSEC_OFFSET, 9);
    }
  });

  test('never adds a real delivery pause of its own: every sendAfterMs gap is unchanged by the offset', () => {
    // A part played alone from the command line is correctly zero-based (AGENT-BRIEF revision 2,
    // item 3), so this call's own first step must still fire immediately (no `sendAfterMs`),
    // whatever `atSecOffset` it is given; a real pause of the offset's size is the CALLER's job
    // (e.g. an inserted `settle`), or it would double-count against that.
    const base = expandFixtureToSteps(fixture, { t0: T0 });
    const offset = expandFixtureToSteps(fixture, { t0: T0, atSecOffset: ATSEC_OFFSET });

    expect(offset[0]?.sendAfterMs).toBeUndefined();

    for (let i = 0; i < base.length; i++) {
      const baseStep = base[i];
      const offsetStep = offset[i];
      if (!baseStep || !offsetStep) throw new Error(`missing step at index ${i}`);
      expect(offsetStep.sendAfterMs ?? 0).toBe(baseStep.sendAfterMs ?? 0);
    }
  });
});

test.describe('planPlayback default anchor (defect 1)', () => {
  // No explicit t0 here: exercises `planner.ts`'s `defaultAnchor` directly.
  test('anchors off the trip\'s own span, not the largest atSec across everything (O17)', () => {
    const fixture = loadFixture('O17');
    const before = Date.now();
    const plan = planPlayback(fixture);
    const after = Date.now();

    // Trip events: IGN_ON..IGN_OFF, max atSec 170. defaultAnchor = now - (170 + 30)s. Bounded
    // rather than pinned to a literal, since "now" is real wall-clock time in this test.
    const maxTripAtSec = 170;
    const marginSec = 30;
    const expectedAnchorLow = before - (maxTripAtSec + marginSec) * 1000;
    const expectedAnchorHigh = after - (maxTripAtSec + marginSec) * 1000;
    expect(plan.t0.getTime()).toBeGreaterThanOrEqual(expectedAnchorLow);
    expect(plan.t0.getTime()).toBeLessThanOrEqual(expectedAnchorHigh);

    // The trip's own last event (IGN_OFF, atSec 170) must stamp safely in the past, not the
    // future: this is the CRITICAL bug this fixes (a naive "now" default, or an anchor computed
    // from the identification's atSec: 93600 instead, either mis-stamp this).
    const ignOff = plan.events.find((e) => e.kind === 'trip' && e.tripEvent?.type === 'IGN_OFF');
    expect(new Date(ignOff!.timestampIso).getTime()).toBeLessThan(before);

    // Identification A (atSec 70, well inside the trip's own span) is also safely in the past.
    const identA = plan.events.find((e) => e.kind === 'ident' && e.identification?.driver === 'A');
    expect(new Date(identA!.timestampIso).getTime()).toBeLessThan(before);
  });

  test('an explicit opts.t0 always wins over the fixture-derived default', () => {
    const fixture = loadFixture('O3.1');
    const explicit = new Date('2020-01-01T00:00:00.000Z');
    const plan = planPlayback(fixture, { t0: explicit });
    expect(plan.t0).toEqual(explicit);
  });
});
